const data = {
    books: [
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
        {
            name:'',
            slug:'',
            image:'',
            price:'' ,
            genre: '',
            description: '',
            countInStock: '',
            listType: '',
        },
    ]
}