const data = {
    books: [
        {
            name:'Front-End Tooling',
            author:'Stefan Baumgartner', 
            slug:'Front-End Tooling',
            image:'',
            price:34.99 ,
            description: 'Front-End Tooling with Gulp, Bower, and Yeoman teaches you how to use and combine these popular tools to set up a customized development workflow from start to finish.',
            countInStock: 16,
            listType: 'Frontend',
        },
        {
            name:'Frontend Development with ASP.net',
            author:'Simone Chiaretta',
            slug:'Frontend Development with ASP.net',
            image:'',
            price:47.59 ,
            description: 'Utilizing the most popular combination of web technologies for Microsoft developers, this guide provides the latest best practices and ASP.NET MVP guidance to get you up to speed quickly.',
            countInStock: 14,
            listType: 'Frontend',
        },
        {
            name:'Modern frontend development',
            author:'Noel Rappin',
            slug:'Modern frontend development',
            image:'',
            price: 47.99 ,
            description: 'Learn to use the Rails 7 tools and simplify the complex JavaScript ecosystem.',
            countInStock:20 ,
            listType: 'Frontend',
        },
        {
            name:'Frontend web development',
            author:'Chris Aquino ',
            slug:'Frontend web development',
            image:'',
            price:31.19 ,
            description: 'Front-end development targets the browser, putting your applications in front of the widest range of users regardless of device or operating system.',
            countInStock: '40',
            listType: 'Frontend',
        },
        {
            name:'Node.js Web Development ',
            author:'David Herron',
            slug:'Node.js Web Development',
            image:'',
            price:'41.84' ,
            description: "Node.js Web Development by David Herron helps you to build scalable web applications using Node.js, Express.js, and the latest ECMAScript techniques. The book takes you through the different stages of developing robust and scalable apps using Node.js 14.",
            countInStock: '0',
            listType: 'Backend',
        },
        {
            name:'RTFM: Red Team Field Manual',
            slug:'RTFM',
            image:'',
            price:'12.59' ,
            description: 'Over 8 years ago, the Red Team Field Manual (RTFM) was born out of operator field notes inspired by years of Red Team missions. While tools and techniques change, operators still constantly find themselves in common operating environments, with time running out. The RTFM has provided a quick reference when there is no time to scour the Internet for that perfect command.',
            countInStock: 0,
            listType: 'Cybersecurity',
        },
        // {
        //     name:'',
        //     slug:'',
        //     image:'',
        //     price:'' ,
        //     description: '',
        //     countInStock: '',
        //     listType: '',
        // },
        // {
        //     name:'',
        //     slug:'',
        //     image:'',
        //     price:'' ,
        //     genre: '',
        //     description: '',
        //     countInStock: '',
        //     listType: '',
        // },
        // {
        //     name:'',
        //     slug:'',
        //     image:'',
        //     price:'' ,
        //     genre: '',
        //     description: '',
        //     countInStock: '',
        //     listType: '',
        // },
        // {
        //     name:'',
        //     slug:'',
        //     image:'',
        //     price:'' ,
        //     description: '',
        //     countInStock: '',
        //     listType: '',
        // },
    ]
}

module.export = data;